### ISSUE TITLE
Your LinkedIn profile says "Japanse"

### ISSUE THREAD

**Issue by alv909** [sholtrop/boterbotTS#15]
Sorry, its not an issue, just didn't know how to reach you without upgrading to LinkedIn Premium, and that would have been overkill.
Congratulations to your Public Speaking Contest - Grand Prize in Japanese that I saw on your LinkedIn page (Honors). Very impressive video on YouTube and interesting presentation. I hope to get that far (N1) one day myself.
However, I noticed it says "Japanse"... on the LinkedIn page, as in "Japanse Public Speaking Contest", shouldn't it be "Japanese"?
Patrick

**Comment by sholtrop** [comment]
Thank you!
